-- Harness stateless DB mode PostgreSQL schema.
--
-- This migration captures the first-class runtime-state tables introduced for
-- DB-backed config, agents, memory, MCP, and skills. It is intentionally kept
-- as plain SQL for operators who apply migrations with psql in PG deployments.

BEGIN;

CREATE TABLE IF NOT EXISTS custom_agents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id VARCHAR(128) NOT NULL,
    agent_name VARCHAR(128) NOT NULL,
    config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    soul_text TEXT NOT NULL DEFAULT '',
    revision INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_custom_agents_owner_name
    ON custom_agents(owner_user_id, agent_name);
CREATE INDEX IF NOT EXISTS ix_custom_agents_owner_user_id
    ON custom_agents(owner_user_id);
CREATE INDEX IF NOT EXISTS ix_custom_agents_agent_name
    ON custom_agents(agent_name);

CREATE TABLE IF NOT EXISTS user_profiles (
    owner_user_id VARCHAR(128) PRIMARY KEY,
    profile_text TEXT NOT NULL DEFAULT '',
    revision INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS default_agent_souls (
    owner_user_id VARCHAR(128) PRIMARY KEY,
    soul_text TEXT NOT NULL DEFAULT '',
    revision INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS memories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id VARCHAR(128) NOT NULL,
    agent_scope VARCHAR(128) NOT NULL DEFAULT '',
    memory_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    schema_version VARCHAR(32) NOT NULL DEFAULT '1.0',
    revision INTEGER NOT NULL DEFAULT 1,
    last_updated TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_memories_owner_agent_scope
    ON memories(owner_user_id, agent_scope);
CREATE INDEX IF NOT EXISTS ix_memories_owner_user_id
    ON memories(owner_user_id);
CREATE INDEX IF NOT EXISTS ix_memories_agent_scope
    ON memories(agent_scope);

CREATE TABLE IF NOT EXISTS mcp_servers (
    name VARCHAR(128) PRIMARY KEY,
    enabled BOOLEAN NOT NULL DEFAULT true,
    transport_type VARCHAR(32) NOT NULL DEFAULT 'stdio',
    command VARCHAR(512),
    args_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    url VARCHAR(2048),
    env_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    headers_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    oauth_json JSONB,
    description TEXT NOT NULL DEFAULT '',
    extra_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    revision INTEGER NOT NULL DEFAULT 1,
    content_hash VARCHAR(64) NOT NULL,
    updated_by VARCHAR(128),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_mcp_servers_content_hash
    ON mcp_servers(content_hash);

CREATE TABLE IF NOT EXISTS runtime_configs (
    "key" VARCHAR(64) PRIMARY KEY,
    payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    schema_version VARCHAR(32) NOT NULL DEFAULT '1',
    revision INTEGER NOT NULL DEFAULT 1,
    content_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by VARCHAR(128)
);

CREATE INDEX IF NOT EXISTS ix_runtime_configs_content_hash
    ON runtime_configs(content_hash);

CREATE TABLE IF NOT EXISTS custom_skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id VARCHAR(128) NOT NULL DEFAULT '',
    skill_name VARCHAR(128) NOT NULL,
    skill_md_text TEXT NOT NULL DEFAULT '',
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    files_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    revision INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_custom_skills_owner_name
    ON custom_skills(owner_user_id, skill_name);
CREATE INDEX IF NOT EXISTS ix_custom_skills_owner_user_id
    ON custom_skills(owner_user_id);
CREATE INDEX IF NOT EXISTS ix_custom_skills_skill_name
    ON custom_skills(skill_name);

CREATE TABLE IF NOT EXISTS skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id VARCHAR(128) NOT NULL DEFAULT '',
    category VARCHAR(32) NOT NULL,
    skill_name VARCHAR(128) NOT NULL,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    enabled BOOLEAN NOT NULL DEFAULT true,
    revision INTEGER NOT NULL DEFAULT 1,
    source VARCHAR(64) NOT NULL DEFAULT 'db',
    content_hash VARCHAR(64) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_skills_owner_category_name
    ON skills(owner_user_id, category, skill_name);
CREATE INDEX IF NOT EXISTS ix_skills_owner_user_id
    ON skills(owner_user_id);
CREATE INDEX IF NOT EXISTS ix_skills_category
    ON skills(category);
CREATE INDEX IF NOT EXISTS ix_skills_skill_name
    ON skills(skill_name);
CREATE INDEX IF NOT EXISTS ix_skills_content_hash
    ON skills(content_hash);

CREATE TABLE IF NOT EXISTS skill_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_id BIGINT NOT NULL,
    relative_path VARCHAR(1024) NOT NULL,
    content_json JSONB NOT NULL,
    mode INTEGER,
    mime_type VARCHAR(128) NOT NULL DEFAULT 'text/plain; charset=utf-8',
    size INTEGER NOT NULL DEFAULT 0,
    content_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_skill_files_skill_path
    ON skill_files(skill_id, relative_path);
CREATE INDEX IF NOT EXISTS ix_skill_files_skill_id
    ON skill_files(skill_id);
CREATE INDEX IF NOT EXISTS ix_skill_files_content_hash
    ON skill_files(content_hash);

CREATE TABLE IF NOT EXISTS custom_skill_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id VARCHAR(128) NOT NULL DEFAULT '',
    skill_name VARCHAR(128) NOT NULL,
    record_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_custom_skill_history_owner_user_id
    ON custom_skill_history(owner_user_id);
CREATE INDEX IF NOT EXISTS ix_custom_skill_history_skill_name
    ON custom_skill_history(skill_name);
CREATE INDEX IF NOT EXISTS ix_custom_skill_history_created_at
    ON custom_skill_history(created_at);

COMMIT;
